input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.pause(200)
    parcours(70, 71)
})
function parcours (vg: number, vd: number) {
    basic.showIcon(IconNames.Square)
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorLeft, Kitronik_Move_Motor.MotorDirection.Forward, vg)
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorRight, Kitronik_Move_Motor.MotorDirection.Forward, vd)
    basic.pause(1500)
    Kitronik_Move_Motor.stop()
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorLeft, Kitronik_Move_Motor.MotorDirection.Forward, vg)
    basic.pause(250)
    Kitronik_Move_Motor.stop()
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorLeft, Kitronik_Move_Motor.MotorDirection.Forward, vg)
    Kitronik_Move_Motor.motorOn(Kitronik_Move_Motor.Motors.MotorRight, Kitronik_Move_Motor.MotorDirection.Forward, vd)
    basic.pause(1000)
    Kitronik_Move_Motor.stop()
}
basic.showIcon(IconNames.Happy)
basic.pause(200)
basic.clearScreen()
